---
# tasks file for alerta_ubuntu

- name: Update the repo
  command: "apt-get update"
  changed_when: false
  become: true


- name: Install Python3 and Other basic packages
  apt:
     name:
         - wget
         - curl
         - python3.7
         - gcc
     state: present
  become: true

- name: Add the apt key for mongoDB
  apt_key:
     url: https://www.mongodb.org/static/pgp/server-4.2.asc
     state: present
  become: true

- name: Adding repo content
  copy:
     content: "deb https://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 main"
     dest: /etc/apt/sources.list.d/mongodb-org-4.2.list
  become: true

- name: Update the repo
  command: "apt-get update"
  changed_when: false
  become: true

- name: Install required packages for the application
  apt:
     name:
        - gettext-base
        - libffi-dev
        - libldap2-dev
        - libpq-dev
        - libsasl2-dev
        - nginx-light
        - postgresql-client
        - python3-dev
        - supervisor
        - mongodb-org-shell
        - python-pip
        - python3-venv
     install_recommends: false
     state: present
  become: true

- name: Install pip latest & venv
  pip:
   name: "{{ item }}"
   executable: pip
   state: present
  become: true
  loop:
      - pip 
      - setuptools
      - virtualenv

- name: Creates a new venv
  command: "python3 -m venv /venv"
  changed_when: false
  become: true

- name: Creating alerta user
  user:
   name: "{{userId}}"
   group: "root"
   system: yes
   # shell: "/sbin/nologin"
   comment: "{{userId}} login User"
   createhome: "no"
   state: present
  become: true

- name: Create a workspace
  file:
      dest: "/{{ item }}"
      state: directory
      mode: 0755
      owner: "{{ userId }}"
      group: "root"
  become: true
  loop:
      - app
      - web

- name: Copy the files
  copy:
      src: "{{ item }}"
      dest: "/app/"
      mode: 0755
      owner: "{{ userId }}"
      group: "root"
  become: true
  loop:
      - install-plugins.sh
      - nginx.conf
      - plugins.txt
      - requirements.txt
      - supervisord.conf
      - uwsgi.ini
      - wsgi.py
      - docker-entrypoint.sh

- name: Install the Setuptools in the virtual env
  pip:
     name: "setuptools"
     state: present
     virtualenv: "/venv"
     virtualenv_python: "3.0"
  become: true

- name: Install python pip packages from requirement.txt
  pip:
     requirements: "/app/requirements.txt"
     virtualenv: "/venv"
     virtualenv_python: "3.0"
     state: present
  become: true

- name: Install the alerta softwares
  pip:
     name:
         - "alerta=={{ CLIENT_VERSION }}"
         - "alerta-server=={{ SERVER_VERSION }}"
     state: present
     virtualenv: "/venv"
     virtualenv_python: "3.0"
  become: true


# - name: Executing the script to install plugins for alerta files
#   shell: "/app/install-plugins.sh"
#   become: true
#   changed_when: false
#   async: 200
#   poll: 50

- name: Downloading the Alerta Web Content
  unarchive:
      src: "https://github.com/alerta/alerta-webui/releases/download/v{{ WEBUI_VERSION }}/alerta-webui.tar.gz"
      dest: /tmp
      remote_src: yes
  become: true

- name: Copy the contect into different location
  shell: "cp -r /tmp/dist/* /web/"
  become: true
  changed_when: false

- name: Copy the config file
  copy:
      src: "config.json"
      dest: "/web/config.json"
      mode: 0755
      owner: "{{ userId }}"
      group: "root"
  become: true

- name: Install MongoDB
  apt:
      name: 
         - mongodb-org
      state: present
  become: true

- name: Start and Enable the mongodb service
  service:
      name: "mongod"
      state: started
      enabled: true
  become: true

- name: Execute Shell entrypoint
  shell: "sudo su -c '/app/docker-entrypoint.sh' - {{ userId }}"
  become: false
  changed_when: false

- name: Execute Shell entrypoint
  shell: "sudo su -c 'supervisord -c /app/supervisord.conf &' - {{ userId }}"
  become: false
 


